export const productsObj = [
  {
    id: 1,
    name: "Женская куртка",
    category: 1,
    subcategory: 2,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1600,
    discount: 30,
    new: true,
  },
  {
    id: 2,
    name: "Мужская куртка",
    category: 2,
    subcategory: 2,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 50,
    new: false,
  },
  {
    id: 3,
    name: "Детский худи",
    category: 3,
    subcategory: 1,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 30,
    new: true,
  },
  {
    id: 4,
    name: "Женская куртка",
    category: 1,
    subcategory: 2,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1600,
    discount: 50,
    new: false,
  },
  {
    id: 5,
    name: "Мужская куртка",
    category: 2,
    subcategory: 2,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 30,
    new: false,
  },
  {
    id: 6,
    name: "Детский худи",
    category: 3,
    subcategory: 1,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 50,
    new: true,
  },
  {
    id: 7,
    name: "Женская куртка",
    category: 1,
    subcategory: 2,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1600,
    discount: 30,
    new: false,
  },
  {
    id: 8,
    name: "Мужская куртка",
    category: 2,
    subcategory: 2,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 30,
    new: false,
  },
  {
    id: 9,
    name: "Детский худи",
    category: 3,
    subcategory: 1,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 50,
    new: true,
  },
  {
    id: 10,
    name: "Женская куртка",
    category: 1,
    subcategory: 2,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1600,
    discount: 50,
    new: false,
  },
  {
    id: 11,
    name: "Мужская куртка",
    category: 2,
    subcategory: 2,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 50,
    new: false,
  },
  {
    id: 12,
    name: "Детский худи",
    category: 3,
    subcategory: 1,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 50,
    new: true,
  },
  {
    id: 13,
    name: "Женская куртка",
    category: 1,
    subcategory: 2,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1600,
    discount: 50,
    new: false,
  },
  {
    id: 14,
    name: "Мужская куртка",
    category: 2,
    subcategory: 2,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 50,
    new: true,
  },
  {
    id: 15,
    name: "Детский худи",
    category: 3,
    subcategory: 1,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 30,
    new: true,
  },
  {
    id: 16,
    name: "Женская куртка",
    category: 1,
    subcategory: 2,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1600,
    discount: 50,
    new: false,
  },
  {
    id: 17,
    name: "Мужская куртка",
    category: 2,
    subcategory: 1,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 50,
    new: true,
  },
  {
    id: 18,
    name: "Детский худи",
    category: 3,
    subcategory: 1,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 30,
    new: true,
  },
  {
    id: 17,
    name: "Мужская куртка",
    category: 2,
    subcategory: 1,
    img: "",
    size: ["s", 'm', 'l', 'xl'],
    colors: ['red', 'green', 'yellow', 'blue'],
    price: 1400,
    discount: 50,
    new: true,
  },
]