export const productsObj = [
    {
        id: 1,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1600,
        discount: 50,
        new: false,
    },
    {
        id: 2,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1300,
        discount: 20,
        new: true,
    },
    {
        id: 3,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1600,
        discount: 0,
        new: true,
    },
    {
        id: 4,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1300,
        discount: 20,
        new: true,
    },
    {
        id: 5,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1600,
        discount: 50,
        new: true,
    },
    {
        id: 6,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1300,
        discount: 20,
        new: true,
    },
    {
        id: 7,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1600,
        discount: 50,
        new: false,
    },
    {
        id: 8,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1300,
        discount: 20,
        new: true,
    },
    {
        id: 9,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1600,
        discount: 0,
        new: true,
    },
    {
        id: 10,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1300,
        discount: 20,
        new: true,
    },
    {
        id: 11,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1600,
        discount: 50,
        new: true,
    },
    {
        id: 12,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1300,
        discount: 20,
        new: true,
    },
    {
        id: 13,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1600,
        discount: 50,
        new: false,
    },
    {
        id: 14,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1300,
        discount: 20,
        new: true,
    },
    {
        id: 15,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1600,
        discount: 0,
        new: true,
    },
    {
        id: 16,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1300,
        discount: 20,
        new: true,
    },
    {
        id: 17,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1600,
        discount: 50,
        new: true,
    },
    {
        id: 18,
        name: "Женская куртка",
        img: "",
        size: ["s", 'm', 'l', 'xl'],
        colors: ['red', 'green', 'yellow', 'blue'],
        price: 1300,
        discount: 20,
        new: true,
    },
]